
name: Deploy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  DeployDevInfrastructure_Stage_DeployInfrastructure:
    name: Deploy Development Infrastructure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Create Resource Groups
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az group create --name ${{ secrets.DEVRESOURCEGROUP }} --location ${{ secrets.LOCATION }} --tags LabInstance=${{ secrets.LABINSTANCEID }}
          az group create --name ${{ secrets.PRODRESOURCEGROUP }} --location ${{ secrets.LOCATION }} --tags LabInstance=${{ secrets.LABINSTANCEID }}

    - name: Deploy Development Infrastructure
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create --resource-group ${{ secrets.DEVRESOURCEGROUP }} --name deployinfradev --template-file ARM-DevSecOps.json

  DeployProdInfrastructure_Stage_DeployInfrastructure:
    name: Deploy Production Infrastructure
    needs: [DeployDevInfrastructure_Stage_DeployInfrastructure]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v2
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy Production Infrastructure
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create --resource-group ${{ secrets.PRODRESOURCEGROUP }} --name deployinfraprod --template-file ARM-DevSecOps-Prod.json
